node.environment=dev
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
# перенаправляем базовую дата-директорию во внутренний /tmp контейнера.
# Скрипт launcher сам создаст внутри папки /tmp/var/log/ и /tmp/var/run/launcher.pid
node.data-dir=/tmp/trino-system-data